自定义协议异常情况测试：
1、假设服务端宕机一段时间重启，检验以下功能是否正常。
   a、客户端是否能够正常发起重连；
   b、重连成功之后，不再重连；
   c、断连期间，心跳定时器停止工作，不再发送心跳请求消息；
   d、服务重启成功之后，允许客户端重新登录；
   e、服务端重启成功之后，客户端重连和握手成功；
   f、重连成功之后，双方的心跳能够正常互发；
   g、性能指标：重连期间，客户端资源得到正常回收，不会导致句柄等资源泄露。

服务端宕机之后，重启之前，客户端周期性重连失败。
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:8080
重连期间线程资源占用正常，内存占用正常。
可以使用jvisualvm工具查看内存和线程情况。
服务端重启成功，握手成功，链路重新恢复。

2、客户端宕机之后，服务端需要能够清除缓存信息，重启之后允许客户端重新登录。
服务端是在LoginAuthRespHandler中清除缓存信息的，只要客户端宕机，服务端的所有handler都会收到异常信息，即
会执行handler里面的exceptionCaught方法。

这个自定义协议对于实际商用协议栈而言，仍然是不足的。例如当链路断连的时候，已经放入发送队列中的消息不能丢失，更加通用的做法是提供通知机制
，将发送失败的消息通知给业务侧，由业务侧决定：是丢弃还是缓存重发。